// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const resetAll = `-- name: ResetAll :exec
DELETE FROM users
`

func (q *Queries) ResetAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAll)
	return err
}
